# name of your application
APPLICATION = lorawan-ble
APPLICATION_VERSION = 0.2.0

# platform for which the application will be built
PLATFORM ?= octa

# Add shields used in application
# Murata
SHIELDS += Murata-dualstack
MURATA_CONNECTOR = 3
LORAWAN_APPLICATION = corona_proof_classroom
USE_BLE = 1

# Path to the octa-stack base directory:
STACKBASE ?= ../..

include $(STACKBASE)/core/Makefile.core